services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-adm
    hostname: portainer-adm
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Santo_Domingo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/netadmin/LabDocker01/docker-stack/portainer-data:/data
    ports:
      - "9000:9000"
    restart: unless-stopped
    network_mode: bridge

  docker-controller-bot:
    image: dgongut/docker-controller-bot:latest
    container_name: docker-bot
    environment:
      - CONTAINER_NAME=docker-bot
      - TELEGRAM_TOKEN=${BOT_TOKEN}
      - TELEGRAM_ADMIN=${CHAT_ID}
      - TZ=America/Santo_Domingo
      - CHECK_UPDATE_EVERY_HOURS=720
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/netadmin/LabDocker01/docker-stack/config:/app/schedule
    restart: always
    network_mode: host
    tty: true

  pihole:
    image: pihole/pihole:latest
    container_name: piholev6
    hostname: piholev6
    networks:
      piholev6-net:
        ipv4_address: 172.20.0.254
      piholeunbound-net: {}
    ports:
      - "8080:80"       # Interfaz web de administración
      - "53:53/tcp"     # DNS TCP para red local
      - "53:53/udp"     # DNS UDP para red local
    environment:
      - TZ=America/Santo_Domingo
      - FTLCONF_WEBSERVER_API_PASSWORD=P@ssword2025*
      - FTLCONF_DNS_UPSTREAMS=unbound#5335
    volumes:
      - /opt/docker/piholev6/etc/pihole:/etc/pihole
      - /opt/docker/piholev6/etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    image: alpinelinux/unbound:latest
    container_name: unbound
    hostname: unbound
    networks:
      piholeunbound-net: {}
    volumes:
      - /opt/docker/piholev6/etc/unbound:/etc/unbound
    restart: unless-stopped

networks:
  piholev6-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

  piholeunbound-net:
    driver: bridge
