services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: PORTAINER-ADM
    hostname: Portainer-ADM
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Santo_Domingo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/netadmin/LabDocker01/docker-stack/portainer-data:/data
    ports:
      - "9000:9000/tcp"
    restart: unless-stopped
    network_mode: bridge

  docker-controller-bot:
    image: dgongut/docker-controller-bot:latest
    container_name: DOCKER-BOT
    environment:
      - CONTAINER_NAME=DOCKER-BOT
      - TELEGRAM_TOKEN=${BOT_TOKEN}
      - TELEGRAM_ADMIN=${CHAT_ID}
      - TZ=America/Santo_Domingo
      - CHECK_UPDATE_EVERY_HOURS=720
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/netadmin/LabDocker01/docker-stack/config:/app/schedule
    restart: always
    network_mode: host
    tty: true

pihole:
    container_name: piholev6
    image: pihole/pihole:latest
    hostname: PIHOLEv6
    networks:
      piholev6-net:
        ipv4_address: 192.168.1.254
      piholeunbound-net:
    environment:
      TZ: 'America/Santo_Domingo'
      FTLCONF_webserver_api_password: 'TuContraseñaSegura'
      FTLCONF_dns_upstreams: 'unbound#5335'
    volumes:
      - '/opt/docker/piholev6/etc/pihole:/etc/pihole'
      - '/opt/docker/piholev6/etc/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    image: alpinelinux/unbound:latest
    container_name: unbound
    hostname: UNBOUND
    networks:
      piholeunbound-net:
    volumes:
      - '/opt/docker/piholev6/etc/unbound:/etc/unbound'
    restart: unless-stopped

networks:
  piholev6-net:
    name: local-network
    external: true
  piholeunbound-net:
    name: piholeunbound-net
