services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - "9000:9000"
    restart: unless-stopped

  docker-controller-bot:
    image: dgongut/docker-controller-bot:latest
    container_name: docker-bot
    hostname: docker-bot
    network_mode: host
    tty: true
    environment:
      TZ: ${TZ}
      CONTAINER_NAME: docker-bot
      TELEGRAM_TOKEN: ${BOT_TOKEN}
      TELEGRAM_ADMIN: ${CHAT_ID}
      CHECK_UPDATE_EVERY_HOURS: 720
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/schedule
    restart: always

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: HomeLab
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-state:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    network_mode: host

volumes:
  tailscale-state:
