services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - "9000:9000"
    restart: unless-stopped

  docker-controller-bot:
    image: dgongut/docker-controller-bot:latest
    container_name: controller-bot
    hostname: controller-bot
    network_mode: host
    tty: true
    environment:
      TZ: ${TZ}
      CONTAINER_NAME: docker-bot
      TELEGRAM_TOKEN: ${BOT_TOKEN}
      TELEGRAM_ADMIN: ${CHAT_ID}
      CHECK_UPDATE_EVERY_HOURS: 720
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/schedule
    restart: always
