  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-adm
    hostname: portainer-adm
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - "9000:9000"
    restart: unless-stopped
    network_mode: bridge

  docker-controller-bot:
    image: dgongut/docker-controller-bot:latest
    container_name: docker-bot
    environment:
      CONTAINER_NAME: docker-bot
      TELEGRAM_TOKEN: ${BOT_TOKEN}
      TELEGRAM_ADMIN: ${CHAT_ID}
      TZ: ${TZ}
      CHECK_UPDATE_EVERY_HOURS: 720
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/schedule
    restart: always
    network_mode: host
    tty: true

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TZ: ${TZ}
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale:/var/lib/tailscale
    network_mode: host
    restart: unless-stopped
